name: deploy-dev

on:
    workflow_dispatch:
    push:
        branches:
            - '*'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  REGISTRY_LOGIN_SERVER: aswincont.azurecr.io
  IMAGE_BASE_NAME: aswinimage
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Development'

    steps:
      - uses: actions/checkout@v2
      
      # Azure Login
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep infrastructure
      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./main.bicep
          parameters: ./parameters/dev.bicepparam

      # Login to Azure Container Registry
      - uses: azure/docker-login@v2
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }} # or use ${{ env.REGISTRY_USERNAME }} if set above
          password: ${{ secrets.REGISTRY_PASSWORD }} # or use ${{ env.REGISTRY_PASSWORD }} if set above


      # Set image version
      - name: Set image version
        id: image-version
        run: echo "version=$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT

      # Build and push Docker image
      - name: Build and push image
        run: |
          docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
          docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:latest
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:latest

      # Deploy to Azure Web App
      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'aswinapp'
          images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}'